package:
  name: q2-stats
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  build:
  - python {{ python }}
  - nodejs
  - setuptools
  - versioningit
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - pandas {{ pandas }}
  - scipy {{ scipy }}
  - jinja2
  - frictionless<=5.5.0
  - statsmodels
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - pytest
  imports:
  - q2_stats
  - qiime2.plugins.stats
  commands:
  - py.test --pyargs q2_stats
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
